version: '4'
services:
  mysqldb:
    image: mysql:8.4.0
    container_name: order_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:     
      - ./mysql:/var/lib/mysql
        